// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: healthcheck/v1/healthcheck.errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthcheckV1ErrorReason int32

const (
	HealthcheckV1ErrorReason_HEALTHCHECK_UNSPECIFIED HealthcheckV1ErrorReason = 0
)

// Enum value maps for HealthcheckV1ErrorReason.
var (
	HealthcheckV1ErrorReason_name = map[int32]string{
		0: "HEALTHCHECK_UNSPECIFIED",
	}
	HealthcheckV1ErrorReason_value = map[string]int32{
		"HEALTHCHECK_UNSPECIFIED": 0,
	}
)

func (x HealthcheckV1ErrorReason) Enum() *HealthcheckV1ErrorReason {
	p := new(HealthcheckV1ErrorReason)
	*p = x
	return p
}

func (x HealthcheckV1ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthcheckV1ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_healthcheck_v1_healthcheck_errors_proto_enumTypes[0].Descriptor()
}

func (HealthcheckV1ErrorReason) Type() protoreflect.EnumType {
	return &file_healthcheck_v1_healthcheck_errors_proto_enumTypes[0]
}

func (x HealthcheckV1ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthcheckV1ErrorReason.Descriptor instead.
func (HealthcheckV1ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_healthcheck_v1_healthcheck_errors_proto_rawDescGZIP(), []int{0}
}

var File_healthcheck_v1_healthcheck_errors_proto protoreflect.FileDescriptor

var file_healthcheck_v1_healthcheck_errors_proto_rawDesc = string([]byte{
	0x0a, 0x27, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x76, 0x31,
	0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2a, 0x37, 0x0a, 0x18, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x31, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x17, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x43,
	0x48, 0x45, 0x43, 0x4b, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x42, 0x63, 0x0a, 0x0e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x74, 0x70, 0x70, 0x2f, 0x67, 0x6f, 0x2d, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2d, 0x62, 0x61, 0x73, 0x65, 0x64, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xa2, 0x02, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_healthcheck_v1_healthcheck_errors_proto_rawDescOnce sync.Once
	file_healthcheck_v1_healthcheck_errors_proto_rawDescData []byte
)

func file_healthcheck_v1_healthcheck_errors_proto_rawDescGZIP() []byte {
	file_healthcheck_v1_healthcheck_errors_proto_rawDescOnce.Do(func() {
		file_healthcheck_v1_healthcheck_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_healthcheck_v1_healthcheck_errors_proto_rawDesc), len(file_healthcheck_v1_healthcheck_errors_proto_rawDesc)))
	})
	return file_healthcheck_v1_healthcheck_errors_proto_rawDescData
}

var file_healthcheck_v1_healthcheck_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_healthcheck_v1_healthcheck_errors_proto_goTypes = []any{
	(HealthcheckV1ErrorReason)(0), // 0: healthcheck.v1.healthcheckV1ErrorReason
}
var file_healthcheck_v1_healthcheck_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_healthcheck_v1_healthcheck_errors_proto_init() }
func file_healthcheck_v1_healthcheck_errors_proto_init() {
	if File_healthcheck_v1_healthcheck_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_healthcheck_v1_healthcheck_errors_proto_rawDesc), len(file_healthcheck_v1_healthcheck_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_healthcheck_v1_healthcheck_errors_proto_goTypes,
		DependencyIndexes: file_healthcheck_v1_healthcheck_errors_proto_depIdxs,
		EnumInfos:         file_healthcheck_v1_healthcheck_errors_proto_enumTypes,
	}.Build()
	File_healthcheck_v1_healthcheck_errors_proto = out.File
	file_healthcheck_v1_healthcheck_errors_proto_goTypes = nil
	file_healthcheck_v1_healthcheck_errors_proto_depIdxs = nil
}
