// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1_errors

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsErrorHealthcheckUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == HealthcheckV1ErrorReason_HEALTHCHECK_UNSPECIFIED.String() && e.Code == 500
}

func ErrorHealthcheckUnspecifiedWithCustomMessage(format string, args ...interface{}) *errors.Error {
	return errors.New(500, HealthcheckV1ErrorReason_HEALTHCHECK_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func ErrorHealthcheckUnspecified() *errors.Error {
	return errors.New(500, HealthcheckV1ErrorReason_HEALTHCHECK_UNSPECIFIED.String(), "Internal server error")
}
