// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/datpp/go-kratos-based-template/internal/biz"
	"github.com/datpp/go-kratos-based-template/internal/conf"
	"github.com/datpp/go-kratos-based-template/internal/data"
	"github.com/datpp/go-kratos-based-template/internal/server"
	"github.com/datpp/go-kratos-based-template/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	healthcheckRepo := data.NewHealthcheckRepo(dataData, logger)
	healthcheckUsecase := biz.NewHealthcheckUsecase(healthcheckRepo, logger)
	healthcheckService := service.NewHealthcheckService(healthcheckUsecase)
	grpcServer := server.NewGRPCServer(confServer, healthcheckService, logger)
	httpServer := server.NewHTTPServer(confServer, healthcheckService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
